GET http://localhost:3001/info
###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/65be29955210acb7454c4702

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "12345"
}

###

DELETE http://localhost:3001/api/persons/65c5fc5e08f544743b753eab